### ISSUE TITLE
ESXi Datastore created with inconsistent size

### ISSUE THREAD

**Issue by adam-ori** [canonical/packer-maas#25]
New to MaaS and ESXI, but have an esxi imge which successfully deploying, but running into an issue where the datastore created and visible within ESXi does not match the size create within the MaaS storage layout.

Maas 2.9 ESXi 7.0.1c

Flow.

Commission new machine ( raid1 pair SSD 250G)
Set storage layout to VMFS6 ( can see 230G assigned to datatore)
Deploy ESXi to machine
Log into ESXi datastore has been created and is 25G but that 200G+ still available
Check disk with partedUtil and can see the remain space available unused.

Checking the deploy logs I can see the following:

get_path_to_storage_volume for volume sda-part3({'device': 'sda', 'id': 'sda-part3', 'name': 'sda-part3', 'number': 3, 'size': '214748364800B', 'type': 'partition', 'uuid': '88a35de9-21b3-4636-a9bc-2e7828679931', 'wipe': 'superblock'})

checking during the install the curtin storage config seems to have all the correct values, not sure how where to troubleshoot this further?

storage:
  config:
  - grub_device: true
    id: sda
    model: LOGICAL VOLUME
    name: sda
    ptable: gpt
    serial: 600508b1001cff732b6d1721777e0839
    type: disk
    wipe: superblock
  - id: sdb
    model: LOGICAL VOLUME
    name: sdb
    serial: 600508b1001c2d384ad8bc1f7f1268f3
    type: disk
    wipe: superblock
  - device: sda
    flag: boot
    id: sda-part1
    name: sda-part1
    number: 1
    offset: 4194304B
    size: 3145728B
    type: partition
    uuid: null
    wipe: superblock
  - device: sda
    id: sda-part2
    name: sda-part2
    number: 2
    size: 4294967296B
    type: partition
    uuid: null
    wipe: superblock
  - device: sda
    id: sda-part3
    name: sda-part3
    number: 3
    size: 214748364800B
    type: partition
    uuid: 88a35de9-21b3-4636-a9bc-2e7828679931
    wipe: superblock
  - devices:
    - sda-part3
    id: datastore1
    name: datastore1
    type: vmfs6
  - device: sda
    id: sda-part5
    name: sda-part5
    number: 5
    size: 261095424B
    type: partition
    uuid: null
    wipe: superblock
  - device: sda
    id: sda-part6
    name: sda-part6
    number: 6
    size: 261095424B
    type: partition
    uuid: null
    wipe: superblock
  - device: sda
    id: sda-part7
    name: sda-part7
    number: 7
    size: 114294784B
    type: partition
    uuid: null
    wipe: superblock
  - device: sda
    id: sda-part8
    name: sda-part8
    number: 8
    size: 298844160B
    type: partition
    uuid: null
    wipe: superblock
  - device: sda
    id: sda-part9
    name: sda-part9
    number: 9
    size: 2684354560B
    type: partition
    uuid: null
    wipe: superblock
  - fstype: vmfs6
    id: datastore1_format
    label: null
    type: format
    uuid: 71460e41-1b75-4ec4-b597-361ad42171c5
    volume: datastore1
  - device: datastore1_format
    id: datastore1_mount
    path: /vmfs/volumes/datastore1
    type: mount
  version: 1

**Comment by Vijaythm** [comment]
I encountered this issue as well, the issue seems to be with get_ending_sector function in storage-esxi, I switched to "partedUtil getUsableSectors" and parse out the ending sector, with ending sector in place I am able to create datastore with the rest of the disk space.

 output = check_output(['partedUtil', 'getUsableSectors', path]).decode()

**Comment by adelhierro** [comment]
So I got this to work all.  So in the storage-esxi file i added this to the main fuctions

`    if len(vmfs_datastores) == 0:
        warn('No storage information given, extending datastore1.')
        extend_default(disks)
    else:
        process_disk_wipes(disks)
        partition_disks(disks, partitions)
        mkvmfs(disks, partitions, vmfs_datastores)
   .    xtend_default(disks) #add this to make datastore1 use all free space`

**Comment by ltrager** [comment]
I just updated the script `storage-esxi` which creates the datastore. It may have fixed this, could you give it a try?

**Comment by adelhierro** [comment]
I will have to give it a go next week.

**Comment by ltrager** [comment]
VMware ESXi 7.0 changed the base OS layout. I added support in de49d4e020b5b9fd043df516d1f96a05be8f552c. You will have to apply the [VMFS7 storage layout to apply an advanced datastore configuration](https://code.launchpad.net/~ltrager/maas/+git/maas/+merge/403705) in MAAS. I'm hoping to land that in MAAS 3.0.1. In the meantime de49d4e020b5b9fd043df516d1f96a05be8f552c will create a datastore using the remaining available space on the boot disk.

**Comment by joaofeteira** [comment]
Hi,

I still have issues with this in both esxi6 and 7  as described here: https://discourse.maas.io/t/maas-3-1-0-beta5-select-vmfs7-storage-layout/5519/3

Any tips?
Thanks

**Comment by joaofeteira** [comment]
> 
> 
> So I got this to work all. So in the storage-esxi file i added this to the main fuctions
> 
> ```
>      if len(vmfs_datastores) == 0:
>         warn('No storage information given, extending datastore1.')
>         extend_default(disks)
>     else:
>         process_disk_wipes(disks)
>         partition_disks(disks, partitions)
>         mkvmfs(disks, partitions, vmfs_datastores)
>         extend_default(disks) #add this to make datastore1 use all free space
> ```

This fix worked for ESXI6.7. the datastore is now the fullsize of the physical disk.
For esxi7 the datastore doesn't even appear
